# Generated by Django 3.1.2 on 2022-09-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20220926_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
