# Generated by Django 3.1.2 on 2022-09-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_auto_20220926_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor',
            new_name='sensor_id',
        ),
    ]
