# Generated by Django 3.1.2 on 2022-09-26 17:33

from django.db import migrations, models
import measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0015_auto_20220926_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.IntegerField(verbose_name=measurement.models.Sensor),
        ),
    ]
